.TH "deprecated" 3 "Sat Apr 25 2015" "Pacparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBglobalScope> Global \fBpacparser_parse_pac\fP (const char *pacfile)\fP" 1c
Use pacparser_parse_pac_file instead\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpacfile\fP PAC file to parse\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on failure and 1 on success\&.
.RE
.PP
.PP

