name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C src
    - name: make dist
      run: |
        DESTDIR=dist make -C src install
        mv src/dist .; mv dist/usr/* dist/; rmdir dist/usr; ls -R dist
    - name: Upload dist
      uses: actions/upload-artifact@v2
      with:
        name: pacparser-${{ matrix.os }}-dist
        path: dist
