name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: make non-windows
      if:  ${{ matrix.os != 'windows-latest' }}
      run: make -C src

    - name: make windows
      if:  ${{ matrix.os == 'windows-latest' }}
      run: make -C src -f Makefile.win32
      
    - name: make non-windows dist
      if:  ${{ matrix.os != 'windows-latest' }}
      run: |
        DESTDIR=dist make -C src install
        mv src/dist .; mv dist/usr/* dist/; rmdir dist/usr; ls -R dist

    - name: make windows dist
      if:  ${{ matrix.os == 'windows-latest' }}
      run: |
        DESTDIR=dist make -C src -f Makefile.win32 dist

    - name: Upload dist
      if:  ${{ matrix.os != 'windows-latest' }}
      uses: actions/upload-artifact@v2
      with:
        name: pacparser-${{ matrix.os }}-dist
        path: src/dist
